alias 7zu='7za a -t7z -m0=lzma -mx=9 -mfb=64 -md=32m -ms=on '
alias C='cd;clear'
alias G='gmplayer  -fs -vf screenshot -ontop '
alias I='pilot-xfer -p /dev/pilot -i  '
alias L='less -FN '
alias M='mplayer  -fs -vf screenshot -ontop '
alias Ms='mplayer -ao none -fs -vf screenshot -ontop '
alias aliases='alias > ~/.aliases.bash'
alias d='duff -P -a -e -l 500k  -r -t . > duff'
alias dump='lynx -dont_wrap_pre -dump '
alias e='emacs -nw --no-init-file --no-site-file   --load ~/.emacs.min'
alias eec='/home/user/.eev/ee.aout'
alias emacsnw='emacs -nw'
alias figlet='figlet -d /usr/share/figlet/'
alias flynx='lynx -force_html '
alias fu='flickr_upload --auth_token 2256612-e80f7b1b59237f2c'
alias l='less '
alias l.='ls -d .* --color=tty'
alias less='less -F '
alias ll='ls -lF --color=tty'
alias ls='ls -F --color=tty'
alias lsd='ls -d */'
alias midi='timidity -Os -A130 -p3 -Ei5 -module=2 -q20 -T140 '
alias miniemacs='emacs -q --no-site-file -l /home/user/.sitelisp/miniemacs.el'
alias mm='mount -o loop -t iso9660 /dev/hdc /mnt/disk'
alias pdf2html='pdftohtml -c -noframes '
alias pilot-xfer='pilot-xfer -p /dev/pilot '
alias pxf='pilot-xfer -p /dev/pilot -i ~/.plucker/*pdb'
alias r='fc -s'
alias s='cd ..'
alias trash='mv -t ~/.local/share/Trash/files --backup=t'
alias ttt='du -h'
alias vi='vim'
# alias which='alias | /usr/bin/which --tty-only --read-alias --show-dot --show-tilde'
alias woot='wget 192.168.2.2:8080'
