alias C='cd;clear'
alias G='gmplayer  -fs -vf screenshot -ontop '
alias I='pilot-xfer -p /dev/pilot -i  '
alias L='less -FN '
alias M='mplayer  -fs -vf screenshot -ontop '
alias Ms='mplayer -ao none -fs -vf screenshot -ontop '
alias aliases='alias > ~/.aliases.bash'
alias l.='ls -d .* --color=tty'
alias l='less '
alias ll='ls -lF --color=tty'
alias ls='ls -F --color=tty'
alias lsd='ls -d */'
alias miniemacs='emacs -q --no-site-file -l /home/user/.sitelisp/miniemacs.el'
alias s='cd ..'
alias woot='wget 192.168.2.2:8080'
